CREATE TABLE CLIENTS
(
	CLIENT_ID SERIAL PRIMARY KEY,
	LAST_NAME CHARACTER VARYING(120) NOT NULL,
	FIRST_NAME CHARACTER VARYING(60) NOT NULL,
	SURNAME CHARACTER VARYING(120),
	BIRTH_DATE DATE NOT NULL,
	NATIONALITY INTEGER REFERENCES DICT_NATIONALITY (ID_CODE) NOT NULL,
	CLIENT_TYPE INTEGER REFERENCES DICT_CLIENT_TYPE (ID_CODE) NOT NULL
);

COMMENT ON TABLE CLIENTS IS 'Клиенты';
COMMENT ON COLUMN CLIENTS.CLIENT_ID IS 'Идентификатор клиента';
COMMENT ON COLUMN CLIENTS.LAST_NAME IS 'Фамилия клиента';
COMMENT ON COLUMN CLIENTS.FIRST_NAME IS 'Имя клиента';
COMMENT ON COLUMN CLIENTS.SURNAME IS 'Отчество клиента';
COMMENT ON COLUMN CLIENTS.BIRTH_DATE IS 'Дата рождения клиента';
COMMENT ON COLUMN CLIENTS.NATIONALITY IS 'Гражданство клиента';
COMMENT ON COLUMN CLIENTS.CLIENT_TYPE IS 'Тип клиента';

INSERT INTO CLIENTS (LAST_NAME, FIRST_NAME, SURNAME, BIRTH_DATE, NATIONALITY, CLIENT_TYPE) VALUES
	('Иванов', 'Иван', 'Иванович', '1979-06-13', 1, 1),
	('Сидоров', 'Василий', 'Петрович', '1955-03-18', 1, 1),
	('Козлов', 'Петр', 'Васильевич', '1968-11-16', 1, 1),
	('Толстой', 'Лев', 'Николаевич', '1990-04-16', 1, 1),
	('Достоевский', 'Федор', 'Михайлович', '1988-08-25', 1, 1);